import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import Value from "@/components/value";
import Gallery from "@/components/gallery";
import Testimonials from "@/components/Testimonials";
import Staps from "@/components/staps";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 min-h-screen flex flex-col"
      >
        <Navbar />
        <Hero />
        <Value />
        <Gallery />
        <Testimonials />
        <Staps />
        <Footer />
        {children}
        
      </body>
    </html>
  );
}
