import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 min-h-screen flex flex-col"
      >
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
